#!/usr/bin/env bash
# Usage:
#  $0 1
####
set -eu

readonly num=$1
readonly myobjdir=out/m/$num
readonly gnuobjdir=out/g/$num

for m in $myobjdir/*.o; do
  basename=${m##*/}
  g=$gnuobjdir/$basename
  echo diff $g $m
  diff $g $m
done
