#!/usr/bin/env bash
#
#  diff outputs of commands for any file
#
#  Usage:
#   $0 out4/reflect readelf --all
#   $0 <basename> <command>
#
###
set -eu

readonly basename=$1
shift
readonly subcmd="$@"

my=${basename}.my.o
gnu=${basename}.gnu.o

echo -- ours
echo ++ theirs
diff -u --color --suppress-common-lines <($subcmd $my) <($subcmd $gnu)
