#!/usr/bin/env bash
set -eu
basename=$1
shift
subcmd="$@"

my=${basename}.my.o
gnu=${basename}.gnu.o

echo -- ours
echo ++ theirs
diff -u --color --suppress-common-lines <($subcmd $my) <($subcmd $gnu)
