#!/usr/bin/env bash
#
#  Encode One-line asm
#
#  Usage:
#    $0 'movq %rax, (%rcx) # comment'
#
###
set -eu

readonly instr=$1
rm -f ./a.out
echo "$instr"
echo "--- as ---"
echo "$instr" | as && objdump -d | tail -n +8
echo "--- ./run ---"
echo "$instr" | ./run && objdump -d | tail -n +8

