#!/usr/bin/env bash
#
# one-line encoder
#
set -e
instr=$1
rm -f ./a.out
echo "$instr"
echo "--- as ---"
echo "$instr" | as && objdump -d | tail -n +8
echo "--- ./run ---"
echo "$instr" | ./run && objdump -d | tail -n +8

