name: Go

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    container: dqneo/ubuntu-build-essential:go
    steps:
      - uses: actions/checkout@v3

      - name: Show versions
        run: as --version

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"

      - name: Test
        run: make test
